export const contributors = {
  authors: [
    "Bruce Mayhew (Author & Project Lead)",
    "Jeff Williams (Author & Original Idea)",
    "Jason White (Architect)",
    "Nanne Baars (Plugin & Platform Architecture)",
    "Richard Lawson (Architect)",
  ],
  designTeam: [
    "Nanne Baars (Plugin & Platform Architecture)",
    "Bruce Mayhew (Goat Herder)",
    "Jason White (User Interface)",
  ],
  sponsors: ["Aspect Security", "Ounce Labs"],
  activeContributors: [
    "Nanne Baars (Developer)",
    "Jason White (Developer)",
    "Doug Morato (Developer & CI)",
    "Bruce Mayhew (Developer)",
    "René Zubcevic (Developer)",
    "Àngel Ollé Blázquez (Developer)",
  ],
  pastContributors: [
    "Richard Lawson (Architect)",
    "Michael Dever (Developer)",
    "Jeff Wayman (Docs)",
    "Dave Cowden (Everything)",
    "Richard Lawson (Service Layer)",
    "Keith Gasser (Survey/Security)",
    "Devin Mayhew (Setup/Admin)",
    "Li Simon (Developer)",
    "Ali Looney (UI Design)",
    "David Anderson (Developer/Design)",
    "Christopher Blum (Lessons)",
    "Laurence Casey (Graphics)",
    "Brian Ciomei (Bug fixes)",
    "Rogan Dawes (Lessons)",
    "Erwin Geirnaert (Solutions)",
    "Aung Knant (Documentation)",
    "Ryan Knell (Lessons)",
    "Christine Koppeit (Build)",
    "Sherif Kousa (Lessons/Documentation)",
    "Reto Lippuner (Lessons)",
    "PartNet (Lessons)",
    "Yiannis Pavlosoglou (Lessons)",
    "Eric Sheridan (Lessons)",
    "Alex Smolen (Lessons)",
    "Chuck Willis (Lessons)",
    "Marcel Wirth (Lessons)",
  ],
};
